name: manual
on:
  workflow_dispatch:
    inputs:
      Name:
        description: Employee Name
        required: true
      DOB:   
        description: DOB
        required: true
      Age:
        description: Age
        required: false
jobs:
   test:
     runs-on: ubuntu-latest
     steps: 
       - name: Get Code
         uses: actions/checkout@v3
       - name: say somthing
         run: echo "Hi, I have been manually triggered!!"
       - run: |
           echo "Name: ${{ github.event.inputs.Name }}"
           echo "DOB: ${{ github.event.inputs.DOB }}"
           echo "Age: ${{ github.event.inputs.Age }}"
